export function Confeiteiras() {
    return(
        <section className="lg:pt-28">
            <img className="h-80 lg:h-auto lg:w-full mt-20 opacity-85 object-cover" src="https://static.wixstatic.com/media/e8274b_1a71ee70a733488bb13b54714aa1d489~mv2.jpg/v1/fill/w_1351,h_748,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/e8274b_1a71ee70a733488bb13b54714aa1d489~mv2.jpg" alt="" />
            <div className="bg-rose-200 text-xl font-thin font-serif text-center ">
                <h2 className="font-mono  text-3xl py-16 font-bold text-center" >Nossa Doce Historia</h2>
                <p className="pb-10 mx-auto  lg:w-8/12 w-11/12">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Suscipit earum nulla perspiciatis impedit optio sint. Corporis neque ullam reiciendis! Ad itaque, dolores molestias ratione mollitia incidunt cum consequuntur maxime molestiae?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Suscipit earum nulla perspiciatis impedit optio sint. Corporis neque ullam reiciendis! Ad itaque, dolores molestias ratione mollitia incidunt cum consequuntur maxime molestiae?</p>
                <p className="pb-10 mx-auto lg:w-8/12 w-11/12">Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis modi explicabo natus mollitia tenetur repellat non, accusamus cum fugiat voluptates quibusdam voluptas quaerat ea dolores veniam exercitationem ipsa labore officiis.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Suscipit earum nulla perspiciatis impedit optio sint. Corporis neque ullam reiciendis! Ad itaque, dolores molestias ratione mollitia incidunt cum consequuntur maxime molestiae?</p>
                <p className="pb-10 mx-auto lg:w-8/12 w-11/12">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, dolorum quos qui molestiae vero, animi minima nulla reprehenderit architecto tempore placeat amet modi harum fuga laudantium nesciunt quia ducimus magnam?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Suscipit earum nulla perspiciatis impedit optio sint. Corporis neque ullam reiciendis! Ad itaque, dolores molestias ratione mollitia incidunt cum consequuntur maxime molestiae?</p>
                <p className="pb-10 mx-auto lg:w-8/12 w-11/12">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, dolorum quos qui molestiae vero, animi minima nulla reprehenderit architecto tempore placeat amet modi harum fuga laudantium nesciunt quia ducimus magnam?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Suscipit earum nulla perspiciatis impedit optio sint. Corporis neque ullam reiciendis! Ad itaque, dolores molestias ratione mollitia incidunt cum consequuntur maxime molestiae?</p>
            </div>
        </section>
    )
}